#############################################
# This compose file is for install testing
# only. It is not meant to be used for
# production. If you are looking for production
# setup, see https://github.com/akkadius/akk-stack
#############################################

version: '2.4'

networks:
  backend:
    driver: bridge

volumes:
  build-cache:

services:
  debian:
    image: akkadius/eqemu-install-v2-test-os:debian-11
    build:
      context: ./containers/debian
    hostname: debian
    tty: true
    volumes:
      - ./:/opt/eqemu-install-v2
      - build-cache:/home/go/.cache/
    environment:
      TZ: America/Chicago
      CGO_ENABLED: 0
      APP_ENV: local
      TERM: xterm-256color
    networks:
      - backend
    command: "/bin/bash -c 'sudo chown go -R /home/go/pkg && go get || true && /bin/bash'"