#############################################
# This compose file is for install testing
# only. It is not meant to be used for
# production. If you are looking for production
# setup, see https://github.com/akkadius/akk-stack
#############################################

version: '2.4'

networks:
  backend:
    driver: bridge

volumes:
  build-cache:

services:


  #############################################
  # go
  #############################################

  go:
    image: akkadius/eqemu-install-v2-go:go-build
    build:
      context: ./containers/go
    hostname: go
    tty: true
    volumes:
      - ./:/opt/eqemu-install-v2
      - build-cache:/home/go/.cache/
    environment:
      TZ: America/Chicago
      CGO_ENABLED: 0
      APP_ENV: local
      TERM: xterm-256color
    ports:
      - 8087:3007
    networks:
      - backend
    command: "/bin/bash -c 'sudo chown go -R /home/go/pkg && go get || true && /bin/bash'"

  #############################################
  # debian 11
  #############################################

  debian-11:
    image: akkadius/eqemu-install-v2-test-os:debian-11
    build:
      context: containers/debian-11
    hostname: debian-11
    tty: true
    volumes:
      - ./:/opt/eqemu-install-v2
      - build-cache:/home/go/.cache/
    environment:
      TZ: America/Chicago
      CGO_ENABLED: 0
      APP_ENV: local
      TERM: xterm-256color
    ports:
      - 8087:3007
    networks:
      - backend
    command: "/bin/bash -c 'sudo chown go -R /home/go/pkg && go get || true && /bin/bash'"

  #############################################
  # debian 12
  #############################################

  debian-12:
    image: akkadius/eqemu-install-v2-test-os:debian-12
    build:
      context: containers/debian-12
    hostname: debian-12
    tty: true
    volumes:
      - ./:/opt/eqemu-install-v2
      - build-cache:/home/go/.cache/
    environment:
      TZ: America/Chicago
      CGO_ENABLED: 0
      APP_ENV: local
      TERM: xterm-256color
    ports:
      - 8087:3007
    networks:
      - backend
    command: "/bin/bash -c 'sudo chown go -R /home/go/pkg && go get || true && /bin/bash'"

  #############################################
  # ubuntu 20.10
  #############################################

  ubuntu-22-10:
    image: akkadius/eqemu-install-v2-test-os:ubuntu-22-10
    build:
      context: ./containers/ubuntu-22-10
    hostname: ubuntu-22-10
    tty: true
    volumes:
      - ./:/opt/eqemu-install-v2
      - build-cache:/home/go/.cache/
    environment:
      TZ: America/Chicago
      CGO_ENABLED: 0
      APP_ENV: local
      TERM: xterm-256color
    ports:
        - 8087:3007
    networks:
      - backend
    command: "/bin/bash -c 'sudo chown go -R /home/go/pkg && go get || true && /bin/bash'"